# Generated by Django 4.1 on 2022-09-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_question_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="YesNoChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_choices",
                    models.CharField(
                        choices=[("Yes", "yes"), ("No", "no"), ("None", "None")],
                        default=None,
                        max_length=4,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.question",
                    ),
                ),
            ],
        ),
    ]
