# Generated by Django 4.1 on 2022-09-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_yesnochoices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YesNoChoices",
        ),
    ]
